version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - test
    environment:
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    networks:
      - app-network
    restart: on-failure  # Optionally restart on failure

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    networks:
      - app-network

  test:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
    environment:
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    networks:
      - app-network
    command: ["mvn", "test"]

networks:
  app-network:
    driver: bridge